name: "Get & Cached Deps"
description: "Get the dependencies (via npm) and Cached"
inputs:
 caching:
  description: "Get the dependencies (via npm) and Cached"
  required: false
  default: 'true'
outputs:
 used-caches:
  description: "Get the dependencies (via npm) and Cached"
  value: ${{ steps.install.outputs.cache }}
runs:
 using: 'composite'
 steps:
  - name: Cache dependencies
    if: inputs.caching == 'true'
    id: cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    id: install
    if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
    run: |
      npm ci
      echo "::set-output name=cache::'${{ inputs.caching }}"
    shell: bash
   